// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTh4P9md9RST4HbgHSw6r7crxGZ__sddU',
    appId: '1:770250167266:web:592d88a50295a7f33e1fbb',
    messagingSenderId: '770250167266',
    projectId: 'expertlink-7eacc',
    authDomain: 'expertlink-7eacc.firebaseapp.com',
    storageBucket: 'expertlink-7eacc.firebasestorage.app',
    measurementId: 'G-V7GPV3KJR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRaBJoufjE5IfXbvWfJRL5jXpN_NWD61Q',
    appId: '1:770250167266:android:133eca63c177ab243e1fbb',
    messagingSenderId: '770250167266',
    projectId: 'expertlink-7eacc',
    storageBucket: 'expertlink-7eacc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwcGzxCxxP5fmzMKQrfW-PQfwoT0GW4oA',
    appId: '1:770250167266:ios:86f87654ddbb19a23e1fbb',
    messagingSenderId: '770250167266',
    projectId: 'expertlink-7eacc',
    storageBucket: 'expertlink-7eacc.firebasestorage.app',
    iosClientId: '770250167266-tc8pc99tbau1kr0b07bdrrslkb1vtkuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.expertlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwcGzxCxxP5fmzMKQrfW-PQfwoT0GW4oA',
    appId: '1:770250167266:ios:86f87654ddbb19a23e1fbb',
    messagingSenderId: '770250167266',
    projectId: 'expertlink-7eacc',
    storageBucket: 'expertlink-7eacc.firebasestorage.app',
    iosClientId: '770250167266-tc8pc99tbau1kr0b07bdrrslkb1vtkuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.expertlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTh4P9md9RST4HbgHSw6r7crxGZ__sddU',
    appId: '1:770250167266:web:3ecbaa2375cc5e2a3e1fbb',
    messagingSenderId: '770250167266',
    projectId: 'expertlink-7eacc',
    authDomain: 'expertlink-7eacc.firebaseapp.com',
    storageBucket: 'expertlink-7eacc.firebasestorage.app',
    measurementId: 'G-DK5KRRDCQT',
  );
}
